### ISSUE TITLE
ブランド作成

### ISSUE THREAD

**Issue by bahihzss** [go-hd/ox#1]
画像に関しては後回しでいいです！

## TODO

- [x] フォーム作成
- [x] フォームを表示するボタン作成
- [x] Firestoreへ追加する処理を実装

## 参考資料

[データベース/brands](https://github.com/go-hd/ox/wiki/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9#brands)
[プロトタイプ](https://main.d1th5xkcq436e3.amplifyapp.com/)

**Comment by bahihzss** [comment]
@tsubono 
こちら来週までに実装できそうでしょうか？

**Comment by tsubono** [comment]
@bahihzss 
来週まで、というのは月曜日までということでしょうか・・？
土日ちょっとバタバタしているので、早くて火曜日アップになりそうです🙇‍♀️

**Comment by bahihzss** [comment]
@tsubono 
なるほど、、
であれば、とりあえずこちらは僕の方でもらいます！
