### ISSUE TITLE
取り込みに使用するCSV把握する

### ISSUE THREAD

**Issue by bahihzss** [go-hd/ox#7]
## 概要

Amazonや楽天などからのデータはAPIが存在しないことが多いためCSVで取り込みます。
このissueでは次の販路での現行のフォーマットでの取り込みを実装します。

#### 売上

- [x] Shopify
- [x] Amazon
- [x] 楽天
- [x] Yahoo!ショッピング
- [x] au Pay マーケット
- [x] ポンパレモール

#### ページビュー

- [x] Shopify
- [x] Amazon
- [x] 楽天
- [x] Yahoo!ショッピング
- [x] au Pay マーケット
- [x] ポンパレモール

#### 広告

- [x] Google
- [x] YDN
- [x] Facebook
- [x] LINE
- [x] AdCent（A8,AT,AFB）
- [x] Logicad
- [x] Yahoo!
- [x] Amazon
- [x] 楽天

**Comment by sushida-suda** [comment]
メモ：https://app.asana.com/0/0/1200051964888688/f

**Comment by sushida-suda** [comment]
``

**Comment by bahihzss** [comment]
Reopen

**Comment by sushida-suda** [comment]
各種csv格納先
https://drive.google.com/drive/folders/1c1oWVan2p-JijwukygTTskB39acZF0B8

**Comment by sushida-suda** [comment]
**メモ**
LINEは現状小田さん入力なし
→商品担当者の手入力？

Shopifyの売上はデバイスごとに出せないので、現状すべてPCに入力
→セッションに関してはデバイスごとに出る

**Comment by sushida-suda** [comment]
@bahihzss 
全部揃ったかと思われます…！

なお、Google広告、FaceBook広告、AdCentに関しては部長が管理している権限とのことだったので、
小田さんにデータを取得してもらいました。

**Comment by bahihzss** [comment]
@sushida-suda ありがとうございます！

**Comment by bahihzss** [comment]
Googleドライブへのアクセス権が欲しいです！

**Comment by sushida-suda** [comment]
@bahihzss 
Asanaみました…
以下に格納し直しています、すいません…！
G.O System > Sales-System > csv
https://drive.google.com/drive/folders/1dLSKiooumVLpiV74h1xI6CF7-3ZRqsY3
